### ISSUE TITLE
Add unit testing for all functions

### ISSUE THREAD

**Issue by bilalbox** [bilalbox/panos_rule_exporter#7]
Add unit tests for each of these functions:

- export.flatten
- export.validate_ip
- export.extract_ip_range
- export.resolve_address
- export.resolve_service

This will allow us to test for all object types and nesting scenarios without having to build an overly complex configuration XML to test against.

**Comment by bilalbox** [comment]
Find out why this nested address group is returning some unknowns....
![image](https://user-images.githubusercontent.com/13258155/37900494-585da014-30bc-11e8-8b79-1c8dadc159ab.png)

**Comment by HighWatersDev** [comment]
Finally, days after I finally came up with pytest file for flatten function. It is at its absolute simplicity but I wanted to commit at least something so we have checks in place for all functions and I will modify it as I'm learning more about testing inshaallaah.

**Comment by bilalbox** [comment]
@HighWatersDev , can you figure out what's not working with these tests? I'd suggest opening another quick bugfix branch from master to fix it:
![image](https://user-images.githubusercontent.com/13258155/38022042-78f8ed9c-324c-11e8-90cd-42e6bef10281.png)

**Comment by HighWatersDev** [comment]
![image](https://user-images.githubusercontent.com/37680855/38025701-4a20bddc-3257-11e8-9511-8eb707c61212.png)

**Comment by HighWatersDev** [comment]
This is just to show I did not just commit a file hoping it'd work. But jazaakallaahu khaira for the hint and pointing it out. I did kind of realize afterwards that I named method inside test_ file with the same name as the main flatten method. I committed the changes directly to master which is probably not the best practice. Inshallaah I shouldn't do it again.
